"""Entry-point placeholder generated by `uv init`.

Superseded by the `src` package layout; kept as the default script entry
point until a later phase removes it.
"""


def main() -> None:
    """Print a startup greeting (placeholder)."""
    print("Hello from fraud-mlops-pipeline!")


if __name__ == "__main__":
    main()
